dist: xenial

language: php

php:
  - '7.2'
  
before_script:
  - sudo apt install mysql-server-5.7
  - sudo systemctl start mysql
  - composer self-update
  - composer install --no-dev
  - php artisan migrate
  #- pear install pear/PHP_CodeSniffer
  
script:
  - vendor/bin/phpunit --coverage-text
  - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
